---
- name: install apache2
  apt: 
    name: apache2
    state: present

- name: install munin-server
  apt:
    name: munin
    state: present

- name: configure munin-server
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    owner: root
    group: root
    mode: 0664
  notify: apache2 restart

- block:
    - lineinfile:
        dest: /etc/munin/apache24.conf
        regexp: '^        Require local'
        line: '        Require all granted'
    
    - lineinfile:
        dest: /etc/munin/apache24.conf
        regexp: '^        Options None'
        line: '        Options FollowSymLinks SymLinksIfOwnerMatch'

    
    - file:
        state: link
        src: /etc/munin/apache24.conf
        dest: /etc/apache2/conf-available/munin.conf

- name: activate munin website 2
  file:
    state: link
    src: /etc/apache2/conf-available/munin.conf
    dest: /etc/apache2/conf-enabled/munin.conf
  notify: apache2 restart