---
- name: install munin
  apt:
    name: munin-node
    state: present

- name: configure munin node
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    owner: root
    group: root
    mode: 0640
  notify: restart munin-node
  
    